- name: Setup Docker and Kubernetes Tools
  hosts: localhost
  become: yes
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
